# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Session-Submitted
version:      1.04
version_from: lib/CGI/Session/Submitted.pm
installdirs:  site
requires:
    Carp:                          0
    CGI::Session:                  1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
